#!/usr/bin/env python3
"""Generate a conservative WordPress Playground Blueprint."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


SLUG = re.compile(r"^[a-z0-9][a-z0-9-]*$")
VERSION = re.compile(r"^(?:latest|[0-9]+(?:\.[0-9A-Za-z_-]+)*)$")


def parse_package(value: str) -> tuple[str, str | None]:
    slug, separator, version = value.partition(":")
    if not SLUG.fullmatch(slug):
        raise argparse.ArgumentTypeError(f"Invalid WordPress.org slug: {slug}")
    if separator and not VERSION.fullmatch(version):
        raise argparse.ArgumentTypeError(f"Invalid version: {version}")
    return slug, version if separator else None


def resource(kind: str, package: tuple[str, str | None]) -> dict[str, str]:
    slug, version = package
    data = {"resource": f"wordpress.org/{kind}", "slug": slug}
    if version:
        data["version"] = version
    return data


def build(args: argparse.Namespace) -> dict[str, Any]:
    steps: list[dict[str, Any]] = []
    for plugin in args.plugin:
        steps.append(
            {
                "step": "installPlugin",
                "pluginData": resource("plugins", plugin),
                "options": {"activate": True},
            }
        )
    for theme in args.theme:
        steps.append(
            {
                "step": "installTheme",
                "themeData": resource("themes", theme),
                "options": {"activate": True},
            }
        )

    return {
        "$schema": "https://playground.wordpress.net/blueprint-schema.json",
        "meta": {
            "title": args.title,
            "description": "Disposable WordPress reproduction generated by Pressolve. Do not add production secrets or customer data.",
            "author": "Pressolve",
            "categories": ["debugging", "testing"],
        },
        "landingPage": "/wp-admin/",
        "preferredVersions": {"php": args.php_version, "wp": args.wp_version},
        "login": True,
        "steps": steps,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--title", default="Pressolve Reproduction Lab")
    parser.add_argument("--wp-version", default="latest")
    parser.add_argument("--php-version", default="8.3")
    parser.add_argument("--plugin", action="append", default=[], type=parse_package, metavar="SLUG[:VERSION]")
    parser.add_argument("--theme", action="append", default=[], type=parse_package, metavar="SLUG[:VERSION]")
    parser.add_argument("--output", type=Path, help="Write JSON to this path instead of stdout")
    args = parser.parse_args()

    if not VERSION.fullmatch(args.wp_version):
        parser.error("--wp-version must be 'latest' or a version")
    if not re.fullmatch(r"[0-9]+\.[0-9]+", args.php_version):
        parser.error("--php-version must look like 8.3")

    text = json.dumps(build(args), indent=2) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
